# Site settings
title: Friends with Benefits
email: lhunath@lyndir.com
description: >
  This is the homepage of the Friends&nbsp;with&nbsp;Benefits World&nbsp;of&nbsp;Warcraft guild.
baseurl: ""
url: "http://friends.fail"
github_username: lhunath
resource_version: 1

# Exclude system files
exclude: [.gitignore]

# Build settings
exclude: [vendor]
markdown: kramdown

# Disqus
disqus_shortname: friends-with-benefits
disqus_publickey: FFFfPIzYpKNVzlWBPdPvfXv0CjkbZap4cRnC6RC79FFAEVpwb7EKtuq4RdR76a30
