# Site settings
title: Friends with Benefits
email: lhunath@lyndir.com
description: >
  This is the homepage of the Friends with Benefits World of Warcraft guild.
baseurl: ""
url: "http://friends.fail"
github_username: lhunath

# Build settings
markdown: kramdown
