#!/usr/bin/env bash
cd "${BASH_SOURCE%/*}"
trap 'rm tmp' EXIT

for member in [A-Z]*.md; do
    name=${member%.md}
    server=$(awk -F': ' '/member-server/{print $2}' "$member")

    printf "Simulating $name..."
    dps=$(/Applications/SimulationCraft/simc armory="us,$server,$name" html="$name-sim.html" | awk -F'[: ]' '/DPS:/ {print $5; exit}')
    echo " $dps DPS"
done
