#!/usr/bin/env bash
set -e

cd "${BASH_SOURCE[0]%/*}"
jekyll build
s3cmd sync --verbose --debug --delete-removed --follow-symlinks --preserve --acl-public --reduced-redundancy _site/ s3://friends.fail/
