#!/usr/bin/env bash
source bashlib

pinf 'Loading member information from the Armory'
json=$(
    curl -s 'https://us.api.battle.net/wow/guild/argent-dawn/Friends%20with%20Benefits?fields=members&locale=en_US&apikey=fm6mz7f4b98efktu3vuqyvpzf2y4sj7p' |
    jq -r '.members | map(select(.rank < 6))[] | .character.name, .character.realm, .character.thumbnail, .rank'
)
fnip
while read -u 3 name && read -u 3 realm && read -u 3 thumb && read -u 3 rank; do
    if [[ -e "$name.md" ]]; then
        pinf 'Updating profile page of %s' "$name"
            realm=${realm// /-} realm=${realm,,}
            thumb=${thumb%-*}
            ex -c "/title:/s/:.*/: $name/e|x" "$name.md"
            ex -c "/member-rank:/s/:.*/: $rank/e|x" "$name.md"
            ex -c "/member-realm:/s/:.*/: $realm/e|x" "$name.md"
            ex -c "/member-armory:/s/:.*/: ${thumb//\//\\\/}/e|x" "$name.md"
        fnip
    else
        wrn 'Missing profile page for %s' "$name"
    fi
done 3<<< "$json"
